[project]
name = "entropy-estimation"
version = "0.1.0"
description = "Entropy Estimation"
dependencies = [
    "pandas",
    "numpy",
    "pyarrow",
    "requests",
    "beautifulsoup4",
    "jupyter>=1.1.1",
]
